name: Revolutionarity
version: 1.3.3
api: 1.0.13
main: de.mariocst.revolutionarity.Revolutionarity
author: marioCST
description: Revolutionarity AntiCheat for Nukkit Servers

permissions:
  revolutionarity.*:
    description: All permissions to this plugin
    default: op
    children:
      revolutionarity.bypass.*: true
      revolutionarity.freeze: true
      revolutionarity.report: true
      revolutionarity.revolutionarity: true
      revolutionarity.staff: true
  revolutionarity.bypass.*:
    description: Bypass all checks
    default: op
    children:
      revolutionarity.bypass.airjump: true
      revolutionarity.bypass.antiimmobile: true
      revolutionarity.bypass.blockreach: true
      revolutionarity.bypass.editionfaker: true
      revolutionarity.bypass.flight: true
      revolutionarity.bypass.glide: true
      revolutionarity.bypass.killaura: true
      revolutionarity.bypass.noswing: true
      revolutionarity.bypass.reach: true
      revolutionarity.bypass.selfhit: true
      revolutionarity.bypass.speed: true
      revolutionarity.bypass.step: true
      revolutionarity.bypass.toolbox: true
  revolutionarity.bypass.airjump:
    description: Bypass airjump check
    default: op
  revolutionarity.bypass.anitimmobile:
    description: Bypass antiimmbile check
    default: op
  revolutionarity.bypass.blockreach:
    description: Bypass blockreach check
    default: op
  revolutionarity.bypass.editionfaker:
    description: Bypass editionfaker check
    default: op
  revolutionarity.bypass.flight:
    description: Bypass flight check
    default: op
  revolutionarity.bypass.glide:
    description: Bypass Glide check
    default: op
  revolutionarity.bypass.killaura:
    description: Bypass killaura check
    default: op
  revolutionarity.bypass.noswing:
    description: Bypass noswing check
    default: op
  revolutionarity.bypass.reach:
    description: Bypass reach check
    default: op
  revolutionarity.bypass.selfhit:
    description: Bypass selfhit check
    default: op
  revolutionarity.bypass.speed:
    description: Bypass speed check
    default: op
  revolutionarity.bypass.step:
    description: Bypass step check
    default: op
  revolutionarity.bypass.toolbox:
    description: Bypass toolbox check
    default: op
  revolutionarity.freeze:
    description: Freeze a player
    default: op
  revolutionarity.report:
    description: Report a player
    default: op
  revolutionarity.revolutionarity:
    description: Revolutionarity command
    default: op
  revolutionarity.staff:
    description: Staff permission
    default: op